### PR TITLE
fix: `issue#44` more `Nest` like error

### LINKED ISSUE #44: even more `Nest` like error
### Discussion

- auto-injectable current
image

Find modules dynamically and fix `Scope [AppModule]` to `Scope [AppModule -> CatModule]`, for example.
Please check the reference below, which is `Nest` native.

---

- nest error
image

### Checklist

- [X] Are you add enough explanations for issue ?
- [X] Did you check if there are other issues with the same content as this issue ?

### PR DESCRIPTION
**Pull request by Nhahan**
## Description
- fix the [issue#44](https://github.com/tiny-nestjs/auto-injectable/issues/44)

Define `classMap` to handle classes and paths that are scanned by the `Importer` class. 
Then, check for any overlapping classes in the `classMap` and display them to the users.

Please check the image below.

image

## References
- https://github.com/tiny-nestjs/auto-injectable/issues/44

## Checklist
- [x] Add labels and reviewers ?
- [x] Are you fully explaining what you changed ?
- [x] Did you check that there is no conflict with the base branch ?

### CODE REVIEW

File: lib/core/importer.ts [hunk 1]
```diff
@@ -90,10 +91,13 @@ export class Importer {
...
   private catchOverlappedScanScope(value: { new (...args: any[]): any; name: string }, pathName: string) {
     locate(value as any).then(({ path }: { path: string }) => {
+      this.classMap.set(path, value);
       if (!this.rootPath) this.rootPath = pathName;
       if (this.rootPath !== path) {
         new Logger('ExceptionHandler').error(
-          `ComponentScan() module scope cannot be overlapped.\n\nPotential causes:\n- An overlapped dependency between modules.\n- Please check the module in '${this.rootPath}' and '${path}'\n\nScope [${value.name}]`,
+          `ComponentScan() module scope cannot be overlapped.\n\nPotential causes:\n- An overlapped dependency between modules.\n- Please check the module in '${
+            this.rootPath
+          }' and '${path}'\n\nScope [${value.name} -> ${this.classMap.get(this.rootPath)!.name}]`,
```
Comment (Nhahan) [inline lib/core/importer.ts:100]: I know some people may dislike `!` syntax. But in this case, `this.rootPath` key is definetely defined, so I used it to make the code short and clear.
Looks fine to me, but if you have a different opinion please let me know. 😄

Comment (player31-kks) [reply lib/core/importer.ts:100]: LGTM

**Review by player31-kks — APPROVED** [review]
